package io.github.kurohi.akachannoise.ui.theme

import androidx.compose.ui.graphics.Color

// Day: soft, warm and quiet — pleasant in daylight without being childish.
val DayBackground = Color(0xFFFDF8F4)
val DaySurface = Color(0xFFFFFDFB)
val DaySurfaceVariant = Color(0xFFF2E7DE)
val DayPrimary = Color(0xFF5F7E9A)
val DayOnPrimary = Color(0xFFFFFFFF)
val DayPrimaryContainer = Color(0xFFD7E5F2)
val DayOnPrimaryContainer = Color(0xFF16324A)
val DaySecondary = Color(0xFFA98A78)
val DayOnSecondary = Color(0xFFFFFFFF)
val DaySecondaryContainer = Color(0xFFF0E0D6)
val DayOnSecondaryContainer = Color(0xFF3D2A20)
val DayTertiary = Color(0xFF7E9C87)
val DayOnTertiary = Color(0xFFFFFFFF)
val DayOnBackground = Color(0xFF2B2622)
val DayOnSurface = Color(0xFF2B2622)
val DayOnSurfaceVariant = Color(0xFF6B5F56)
val DayOutline = Color(0xFFB9A99D)

// Night: deep navy, dim and calm for a dark nursery.
val NightBackground = Color(0xFF10151B)
val NightSurface = Color(0xFF171E26)
val NightSurfaceVariant = Color(0xFF232C36)
val NightPrimary = Color(0xFFA7C3DC)
val NightOnPrimary = Color(0xFF0E2233)
val NightPrimaryContainer = Color(0xFF2C4356)
val NightOnPrimaryContainer = Color(0xFFD3E4F5)
val NightSecondary = Color(0xFFD3B9A8)
val NightOnSecondary = Color(0xFF33231A)
val NightSecondaryContainer = Color(0xFF4A362A)
val NightOnSecondaryContainer = Color(0xFFF1DFD3)
val NightTertiary = Color(0xFFA8C7B3)
val NightOnTertiary = Color(0xFF17291F)
val NightOnBackground = Color(0xFFE3E6EA)
val NightOnSurface = Color(0xFFE3E6EA)
val NightOnSurfaceVariant = Color(0xFFB4BCC4)
val NightOutline = Color(0xFF6E7883)

// Night-red: true black with dim red/amber — preserves night vision at 3 AM.
val NightRedBackground = Color(0xFF000000)
val NightRedSurface = Color(0xFF0A0403)
val NightRedSurfaceVariant = Color(0xFF1A0A06)
val NightRedPrimary = Color(0xFFB4463A)
val NightRedOnPrimary = Color(0xFF140302)
val NightRedPrimaryContainer = Color(0xFF3A120C)
val NightRedOnPrimaryContainer = Color(0xFFE0A79B)
val NightRedSecondary = Color(0xFF8E4632)
val NightRedOnSecondary = Color(0xFF120301)
val NightRedSecondaryContainer = Color(0xFF2A0F09)
val NightRedOnSecondaryContainer = Color(0xFFCFA08F)
val NightRedTertiary = Color(0xFFA9722F)
val NightRedOnTertiary = Color(0xFF120A02)
val NightRedOnBackground = Color(0xFFC0705F)
val NightRedOnSurface = Color(0xFFC0705F)
val NightRedOnSurfaceVariant = Color(0xFF8E5446)
val NightRedOutline = Color(0xFF5E332A)
